
/*create table category (
                          id bigint generated by default as identity,
                          description varchar(255),
                          primary key (id)
);


create table ingredient (
                            id bigint generated by default as identity,
                            amount numeric(19,2),
                            description varchar(255),
                            recipe_id bigint,
                            uom_id bigint,
                            primary key (id)
);


create table notes (
                       id bigint generated by default as identity,
                       recipe_notes clob,
                       recipe_id bigint,
                       primary key (id)
);


create table recipe (
                        id bigint generated by default as identity,
                        cook_time integer,
                        description varchar(255),
                        difficulty varchar(255),
                        directions varchar(255),
                        image blob,
                        prep_time integer,
                        servings integer,
                        url varchar(255),
                        notes_id bigint,
                        primary key (id)
);


create table recipe_category (
                                 recipe_id bigint not null,
                                 category_id bigint not null,
                                 primary key (recipe_id, category_id)
);

create table unit_of_measure (
                                 id bigint generated by default as identity,
                                 description varchar(255),
                                 primary key (id)
);



INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');
INSERT INTO unit_of_measure (description) VALUES ('Ounce');
*/



